In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies2020_updated.csv')
# for year 2020 data set we have to delete 40th row
#df = df.drop([40],axis = 0)
df

,Title,Director,Cast,genres,combo
0,beautiful,agasthya manju,Parth Suri Naina Ganguly,Drama,beautiful agasthya manju Parth Suri Naina Gang...
1,oollalla oollalla,satya prakash,Nataraj Noorin Shereef Ankeeta R Maharanaa,un_known,oollalla oollalla satya prakash Nataraj Noorin...
2,utthara,sr thirupathi,Sreeram Karronya Katrynn Ajay Ghosh,un_known,utthara sr thirupathi Sreeram Karronya Katrynn...
3,wifei,gssp kalyan,Abhishek Reddy Sakshi Sidiya Kavya,Comedy,wifei gssp kalyan Abhishek Reddy Sakshi Sidiya...
4,sarileru neekevvaru,anil ravipudi,Mahesh Babu Rashmika Mandanna Vijayashanti Pra...,Action,sarileru neekevvaru anil ravipudi Mahesh Babu ...
...,...,...,...,...,...
57,guvva gorinka,bammidi mohan,Satyadev Kancharana Priyaa Lal Chaitanya Madhu...,Romance,guvva gorinka bammidi mohan Satyadev Kancharan...
58,dirty hari,m. s. raju,Shravan Reddy Ruhani Sharma Ajay,Thriller Romance,dirty hari m. s. raju Shravan Reddy Ruhani Sha...
59,murder,anand chandra,Avancha Sahiti Krishnaswamy Srikanth,Drama Horror,murder anand chandra Avancha Sahiti Krishnaswa...
60,solo brathuke so better,subbu,Sai Dharam Tej Nabha Natesh Rajendra Prasad,Comedy Romance,solo brathuke so better subbu Sai Dharam Tej N...
61,oka yodhudu,haari,NaN,un_known,NaN

In [2]:
df = df.reset_index(drop=True)

In [3]:
df1 = pd.read_csv('cast2021.csv')
df1

                                                 cast
0   Ravi Teja Shruti Haasan Varalaxmi Sarathkumar ...
1   Priyadarshi Pulikonda Harshith Malgireddy Mani...
2   Ram Pothineni Nivetha Pethuraj Malvika Sharma ...
3   Bellamkonda Sreenivas Nabha Natesh Anu Emmanue...
4   Punarnavi Bhupalam Mahat Raghavendra Sudarshan...
..                                                ...
61  Allu Arjun Rashmika Mandanna Jagapathi Babu Pr...
62  Sharwanand Siddharth Aditi Rao Hydari Anu Emma...
63      Venkatesh Varun Tej Tamannaah Mehreen Pirzada
64  Vijay Deverakonda Ananya Panday Ramya Krishna ...
65  N. T. Rama Rao Jr Ram Charan Ajay Devgn Alia B...

[66 rows x 1 columns]

In [4]:
df['Cast'] = df1['cast']

df = df.drop(['genres','combo'], axis =1)

In [5]:
df['combo'] = df['Title']+' '+df['Director']+' '+df['Cast']+' '+df['genres']

In [6]:
df

,Title,Director,Cast,genres,combo
0,krack,gopichand malineni,Ravi Teja Shruti Haasan Varalaxmi Sarathkumar ...,un_known,krack gopichand malineni Ravi Teja Shruti Haas...
1,mail,uday gurrala,Priyadarshi Pulikonda Harshith Malgireddy Mani...,Comedy Romance,mail uday gurrala Priyadarshi Pulikonda Harshi...
2,red,kishore tirumala,Ram Pothineni Nivetha Pethuraj Malvika Sharma ...,Drama Thriller,red kishore tirumala Ram Pothineni Nivetha Pet...
3,alludu adhurs,santhosh srinivas,Bellamkonda Sreenivas Nabha Natesh Anu Emmanue...,Romance Comedy,alludu adhurs santhosh srinivas Bellamkonda Sr...
4,cycle,aatla arjun reddy,Punarnavi Bhupalam Mahat Raghavendra Sudarshan...,Drama,cycle aatla arjun reddy Punarnavi Bhupalam Mah...
...,...,...,...,...,...
61,pushpa,sukumar,Allu Arjun Rashmika Mandanna Jagapathi Babu Pr...,un_known,pushpa sukumar Allu Arjun Rashmika Mandanna Ja...
62,maha samudram,ajay bhupathi,Sharwanand Siddharth Aditi Rao Hydari Anu Emma...,un_known,maha samudram ajay bhupathi Sharwanand Siddhar...
63,f3Â : fun and frustration,anil ravipudi,Venkatesh Varun Tej Tamannaah Mehreen Pirzada,Comedy Romance,f3Â : fun and frustration anil ravipudi Venkate...
64,liger,puri jagannadh,Vijay Deverakonda Ananya Panday Ramya Krishna ...,un_known,liger puri jagannadh Vijay Deverakonda Ananya ...
65,rrr,s. s. rajamouli,N. T. Rama Rao Jr Ram Charan Ajay Devgn Alia B...,Comedy,rrr s. s. rajamouli N. T. Rama Rao Jr Ram Char...

In [7]:
df.to_csv('movies2021_updated.csv', index = False)

In [8]:
dt = pd.read_csv('movies2021_updated.csv')
dt

,Title,Director,Cast,genres,combo
0,krack,gopichand malineni,Ravi Teja Shruti Haasan Varalaxmi Sarathkumar ...,un_known,krack gopichand malineni Ravi Teja Shruti Haas...
1,mail,uday gurrala,Priyadarshi Pulikonda Harshith Malgireddy Mani...,Comedy Romance,mail uday gurrala Priyadarshi Pulikonda Harshi...
2,red,kishore tirumala,Ram Pothineni Nivetha Pethuraj Malvika Sharma ...,Drama Thriller,red kishore tirumala Ram Pothineni Nivetha Pet...
3,alludu adhurs,santhosh srinivas,Bellamkonda Sreenivas Nabha Natesh Anu Emmanue...,Romance Comedy,alludu adhurs santhosh srinivas Bellamkonda Sr...
4,cycle,aatla arjun reddy,Punarnavi Bhupalam Mahat Raghavendra Sudarshan...,Drama,cycle aatla arjun reddy Punarnavi Bhupalam Mah...
...,...,...,...,...,...
61,pushpa,sukumar,Allu Arjun Rashmika Mandanna Jagapathi Babu Pr...,un_known,pushpa sukumar Allu Arjun Rashmika Mandanna Ja...
62,maha samudram,ajay bhupathi,Sharwanand Siddharth Aditi Rao Hydari Anu Emma...,un_known,maha samudram ajay bhupathi Sharwanand Siddhar...
63,f3Â : fun and frustration,anil ravipudi,Venkatesh Varun Tej Tamannaah Mehreen Pirzada,Comedy Romance,f3Â : fun and frustration anil ravipudi Venkate...
64,liger,puri jagannadh,Vijay Deverakonda Ananya Panday Ramya Krishna ...,un_known,liger puri jagannadh Vijay Deverakonda Ananya ...
65,rrr,s. s. rajamouli,N. T. Rama Rao Jr Ram Charan Ajay Devgn Alia B...,Comedy,rrr s. s. rajamouli N. T. Rama Rao Jr Ram Char...